[package]
name = "flute"
version = "0.1.0"
edition = "2024"

[dependencies]
snafu = "0.9.1"
serde = { version = "1.0.228", features = ["derive"] }
futures-util = { version = "0.3.31", optional = true, default-features = false, features = [
    "std",
    "sink",
] }
kanal = { version = "0.1.1", optional = true }
postcard = { version = "1.1.3", optional = true, features = ["use-std"] }
serde_json = { version = "1.0.149", optional = true }
tokio = { version = "1.50", optional = true, features = ["rt"] }
gloo-net = { version = "0.6.0", optional = true, default-features = false, features = [
    "http",
    "websocket",
] }

axum = { version = "0.8.8", optional = true }


[features]
examples = [
    "dep:axum",
    "dep:tokio",
    "tokio/full",
    "futures",
    "kanal",
    "data-json",
]

futures = ["dep:futures-util"]
kanal = ["dep:kanal"]
wasm = ["dep:gloo-net"]

data-json = ["dep:serde_json"]
data-postcard = ["dep:postcard"]

fast-server = ["dep:tokio"]
unstable-split-any = ["futures", "futures-util/unstable", "futures-util/bilock"]
